import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
// Generated by `prisma generate` from prisma/schema.prisma's `output` path.
// Not checked into git (see .gitignore) — run `npm run db:generate` after
// cloning or after any schema change.
import { PrismaClient } from "../../generated/prisma/client";

if (!process.env.DATABASE_URL) {
  throw new Error(
    "DATABASE_URL is not set. Copy .env.example to .env and set it before starting the server."
  );
}

// PrismaPg takes a pg.Pool instance, not a raw connection string — passing
// the string directly to PrismaPg silently produces a pool with no actual
// connection info and fails with a confusing SASL/auth error instead of a
// clear "no connection string" one. The Pool has to be constructed first.
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);

/**
 * Single shared Prisma client for the whole process. Prisma 7 requires a
 * driver adapter to be passed explicitly (there's no default/implicit
 * connection), which is what `adapter` above is for. Reusing this one pg
 * Pool across the app (rather than one per request) is what actually
 * gives you connection pooling — creating a new Pool per request would
 * open a new set of connections every time and quickly exhaust Postgres's
 * connection limit.
 *
 * Import this everywhere the app needs the database — never construct a
 * second PrismaClient/Pool.
 */
export const prisma = new PrismaClient({ adapter });
